name: thor_request_dart
description: This package enables you to talk to VeChain blockchain without hassle. 
version: 1.1.0
repository: https://github.com/SayNode/thor-request.dart/tree/master/thor_request_dart

environment:
  sdk: "^3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  convert: ^3.1.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  nock: ^1.2.3
  pointycastle: ^3.7.4
  thor_devkit_dart: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:
   assets:
    - assets/vtho_abi.json
    - assets/json_test/
