name: thor_request_dart
description: This package enables you to talk to VeChain blockchain without hassle. 
version: 1.1.0
publish_to: none

environment:
  sdk: "^3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.2
  convert: ^3.1.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  nock: ^1.2.3
  pointycastle: ^3.7.3
  thor_devkit_dart:
    git:
      url: https://github.com/ArunBabu98/thor-devkit.dart
      ref: securus


dev_dependencies:
  test: ^1.24.7
  flutter_lints: ^2.0.3


flutter:
   assets:
    - assets/vtho_abi.json
    - assets/json_test/
